import os, math

import ROOT
from ROOT import TFile, TH1F

import pprint
import yaml

from modules import myutils

# ----------------------------------------------------------------------------
# Load config (same as test_tau_reco_tree.py)
default_config = "config/default/taurecolong.yaml"
outputbasepath = "Results/TauReco/"

general_configs = myutils.setup_analysis_config(default_config, outputbasepath)

loggers = general_configs["loggers"]
run_config = general_configs["config"]

logger_config = loggers["config"]
logger_io = loggers["io"]
logger_process = loggers["processing"]

selectDecay = general_configs["decay"]
outputpath = general_configs["outputpath"]

logger_config.info("Configuration loaded!")
logger_config.info("Configuration:\n%s", pprint.pformat(general_configs, indent=4))

# Input: TTree file generated by test_tau_reco_tree.py
tree_filename = "Tree_" + general_configs["fileOutName"]
tree_filepath = os.path.join(outputpath, tree_filename)

logger_io.info("Opening TTree file: %s", tree_filepath)
infile = TFile(tree_filepath, "READ")
if infile.IsZombie():
    raise RuntimeError("Could not open input file: %s" % tree_filepath)

Tau_tree = infile.Get("Tau_tree")
if not Tau_tree:
    raise RuntimeError("Could not find Tau_tree in file: %s" % tree_filepath)

logger_io.info("TTree has %d entries", Tau_tree.GetEntries())

# Output histograms file
hist_filename = "Hist_" + general_configs["fileOutName"]
hist_filepath = os.path.join(outputpath, hist_filename)

# ----------------------------------------------------------------------------
# Define histograms (same as simple_taureco_test.py)

# Gen Level
hGenTauPt    = TH1F("histoGenTauPt",    "", 250, 0, 50)
hGenTauVisPt = TH1F("histoGenTauVisPt", "", 250, 0, 50)
hGenTauP     = TH1F("histoGenTauP",     "", 250, 0, 50)
hGenTauVisP  = TH1F("histoGenTauVisP",  "", 250, 0, 50)

# Decay Type
hGenTauType  = TH1F("histoGenTauType",  "", 41, -21, 20)

# Mass
hGenTauMass    = TH1F("histoGenTauMass",    "", 500, 0, 10)
hGenTauVisMass = TH1F("histoGenTauVisMass", "", 500, 0, 10)

# Reco Level
hRecoTauPt   = TH1F("histoRecoTauPt",   "", 250, 0, 50)
hRecoTauP    = TH1F("histoRecoTauP",    "", 250, 0, 50)

# Decay Type
hRecoTauType = TH1F("histoRecoTauType", "", 41, -21, 20)

# Mass
hRecoTauMass = TH1F("histoRecoTauMass", "", 500, 0, 10)

# Resolution
hResTauP     = TH1F("histoResTauP",     "", 500, -1, 1)

# ----------------------------------------------------------------------------
# Loop over TTree entries

countEvents = 0
for entry in Tau_tree:
    if countEvents % 1000 == 0:
        logger_process.info("Processing event %d", countEvents)
    countEvents += 1

    nGenTaus  = entry.numGenTaus

    # ---- Gen taus ----
    for i in range(nGenTaus):
        hGenTauPt.Fill(entry.GenTauPt[i])
        hGenTauVisPt.Fill(entry.GenVisTauPt[i])
        hGenTauP.Fill(entry.GenTauP[i])
        hGenTauVisP.Fill(entry.GenVisTauP[i])
        hGenTauType.Fill(entry.GenTauType[i])
        hGenTauMass.Fill(entry.GenTauMass[i])
        hGenTauVisMass.Fill(entry.GenVisTauMass[i])

    # ---- Reco taus ----
    nRecoTaus = len(entry.RecoTauP)
    for i in range(nRecoTaus):
        hRecoTauPt.Fill(entry.RecoTauPt[i])
        hRecoTauP.Fill(entry.RecoTauP[i])
        hRecoTauType.Fill(entry.RecoTauDM[i])  # RecoTauDM is already the normalized decay mode
        hRecoTauMass.Fill(entry.RecoTauMass[i])

    # ---- Resolution: matched gen-reco pairs ----
    # RecoMatchedKey[i] is the reco index matched to gen tau i (-1 if unmatched)
    for i in range(nGenTaus):
        matched_reco_idx = entry.RecoMatchedKey[i]
        if matched_reco_idx == -1:
            continue
        gen_vis_p = entry.GenVisTauP[i]
        reco_p    = entry.RecoTauP[matched_reco_idx]
        if gen_vis_p > 0:
            hResTauP.Fill((reco_p - gen_vis_p) / gen_vis_p)

logger_process.info("Processed %d events", countEvents)

# ----------------------------------------------------------------------------
# Write output

outfile = TFile(hist_filepath, "RECREATE")

hGenTauPt.Write()
hGenTauVisPt.Write()
hGenTauP.Write()
hGenTauVisP.Write()
hGenTauType.Write()
hGenTauMass.Write()
hGenTauVisMass.Write()

hRecoTauPt.Write()
hRecoTauP.Write()
hRecoTauType.Write()
hRecoTauMass.Write()

hResTauP.Write()

outfile.Close()
infile.Close()

logger_io.info("Histograms written to %s", hist_filepath)
logger_io.info("End of job")
