datasets:
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/ILD_reco_a1_optcuts.root
    label: SM
    color: ROOT.kBlack
    linestyle: 1
    markerstyle: 20
    markersize: 1.0
    linewidth: 3
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/ILD_reco_a1_optcuts.root
    label: A_tau=+1
    color: ROOT.kRed
    linestyle: 2
    markerstyle: 21
    markersize: 1.0
    linewidth: 3
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/ILD_reco_a1_optcuts.root
    label: A_tau=-1
    color: ROOT.kBlue
    linestyle: 2
    markerstyle: 22
    markersize: 1.0
    linewidth: 3

plots:
  templates_ILD:
    per_dataset:
      'SM': Optimal_X_dec0_SIGNAL_SIGNAL
      'A_tau=+1': Optimal_X_dec0_SIGNAL_SIGNAL_corr_M1
      'A_tau=-1': Optimal_X_dec0_SIGNAL_SIGNAL_corr_P1
    title: '\text{ILD: reweighted templates, } a_{1}^{\pm} + \ell'
    x: 'z_{a_{1}}'
    y: 'Norm. events'
    normalize: "integral"
    legend: [0.60, 0.72, 0.90, 0.90]
