datasets:
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/CLD_reco_rho_lep_optcuts.root
    label: CLD reco
    color: ROOT.kRed
    linestyle: 1
    markerstyle: 20
    markersize: 1.0
    linewidth: 3
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/ILD_reco_rho_lep_optcuts.root
    label: ILD reco
    color: ROOT.kBlue
    linestyle: 1
    markerstyle: 21
    markersize: 1.0
    linewidth: 3

plots:
  optvar_reco_signal:
    per_dataset:
      'CLD reco': Omega_Reco_dec0_SIGNAL_SIGNAL
      'ILD reco': Omega_Reco_dec0_SIGNAL_SIGNAL
    title: '\text{Optimal variable, } \rho^{\pm} + \ell \text{ (signal)}'
    x: '\omega_{\rho}'
    y: 'Norm. events'
    normalize: "integral"
    legend: [0.60, 0.72, 0.90, 0.90]
  optvar_reco_allall:
    per_dataset:
      'CLD reco': Omega_Reco_dec0_ALL_ALL
      'ILD reco': Omega_Reco_dec0_ALL_ALL
    title: '\text{Optimal variable, } \rho^{\pm} + \ell \text{ (all selected)}'
    x: '\omega_{\rho}'
    y: 'Norm. events'
    normalize: "integral"
    legend: [0.60, 0.72, 0.90, 0.90]
