datasets:
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/CLD_gen_rho_lep_nocuts.root
    label: CLD gen
    color: ROOT.kOrange+7
    linestyle: 1
    markerstyle: 24
    markersize: 1.0
    linewidth: 3
  - path: /nfs/cms/arqolmo/TausFCCee/TauPolOutputs/CLD_ILD/merged_histos/ILD_gen_rho_lep_nocuts.root
    label: ILD gen
    color: ROOT.kAzure+7
    linestyle: 1
    markerstyle: 25
    markersize: 1.0
    linewidth: 3

plots:
  optvar_gen_signal:
    per_dataset:
      'CLD gen': Omega_Reco_dec0_SIGNAL_SIGNAL
      'ILD gen': Omega_Reco_dec0_SIGNAL_SIGNAL
    title: '\text{Optimal variable, } \rho^{\pm} + \ell \text{ (signal)}'
    x: '\omega_{\rho}'
    y: 'Norm. events'
    normalize: "integral"
    legend: [0.60, 0.72, 0.90, 0.90]
  optvar_gen_allall:
    per_dataset:
      'CLD gen': Omega_Reco_dec0_ALL_ALL
      'ILD gen': Omega_Reco_dec0_ALL_ALL
    title: '\text{Optimal variable, } \rho^{\pm} + \ell \text{ (all selected)}'
    x: '\omega_{\rho}'
    y: 'Norm. events'
    normalize: "integral"
    legend: [0.60, 0.72, 0.90, 0.90]
